name: obx
description: Transparent Refined Reactive State(less) Management
version: 0.0.1
publish_to: none

environment:
  sdk: '>=3.1.3 <4.0.0'
  flutter: ">=1.17.0"


dependencies:
  flutter:
    sdk: flutter
  collection: ^1.16.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  get: ^5.0.0-beta.52
  equatable: ^2.0.5
  benchmark_harness: ^2.2.0

flutter:
